server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/carshop
    username: admin
    password: ylab
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.springframework.transaction: TRACE